OS:OSX
language: swift
osx_image: xcode13.2
script: 'xcodebuild clean test -workspace CodeChallengeIOS.xcworkspace -scheme "CodeChallengeIOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO'
notifications:
    email:
        recipients:
            - hungnt1486@gmail.com
            - hung@modmo.io
        on_success: always
        on_failure: always
        
before_install:
  - bundle install
  - bundle exec pod install --repo-update
